BlogBundle\Entity\Post:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [englishTitle]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [frenchTitle]
        - Callback: validate

    properties:
        englishTitle:
            - Type: string
            - NotBlank: ~
            - Length:
                min: 10
                max: 150

        frenchTitle:
            - Type: string
            - NotBlank: ~
            - Length:
                min: 10
                max: 150

        englishAbstract:
            - Type: string
            - NotBlank: ~
            - Length:
                min: 150
                max: 255

        frenchAbstract:
            - Type: string
            - NotBlank: ~
            - Length:
                min: 150
                max: 255

        englishContent:
            - Type: string

        frenchContent:
            - Type: string

        cover:
            - Url:
                protocols: [http, https]
            - Length:
                min: 10
                max: 150

        category:
            - Type: string
            - Choice:
                choices: ['travel', 'running', 'vanlife']

        publication:
            - Type: DateTime

        status:
            - Type: string
            - Choice:
                choices: ['draft', 'back-log', 'published', 'deleted']