BlogBundle\Entity\Post:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [title]
        - Callback: validate

    properties:
        title:
            - Type: string
            - NotBlank: ~
            - Length:
                min: 10
                max: 150

        content:
            - Type: string

        category:
            - Type: string
            - Choice:
                choices: ['travel', 'running', 'vanlife']

        publication:
            - Type: DateTime

        status:
            - Type: string
            - Choice:
                choices: ['active', 'pending', 'deleted']