fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address:        theusualdreamers@gmail.com
        sender_name:    The Usual Dreamers