# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host:      "%mailer_host%"
    username:  "%mailer_username%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    delivery_address: "%mailer_dev_recipient%"