imports:
    - { resource: parameters_prod.php }
    - { resource: config.yml }

# Monolog
monolog:
    handlers:
        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      deduplicated
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
             type:       swift_mailer
             from_email: 'theusualdreamers@gmail.com'
             to_email:   'theusualdreamers@gmail.com'
             subject:    '[PROD LOG] An Error Occurred! %%message%%'
             level:      debug
             formatter:  monolog.formatter.html
             content_type: text/html

swiftmailer:
    transport: smtp
    host:      smtp.sendgrid.net
    username:  "%mailer_username%"
    password:  "%mailer_password%"
    auth_mode: login
    port:      587
    encryption: tls