imports:
    - { resource: parameters_prod.php }
    - { resource: config.yml }

# Monolog
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type:  console
        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      buffered
        buffered:
            type:    buffer
            handler: swift
        swift:
             type:       swift_mailer
             from_email: 'theusualdreamers@gmail.com'
             to_email:   'theusualdreamers@gmail.com'
             subject:    '[PROD LOG] An Error Occurred! %%message%%'
             level:      debug
             formatter:  monolog.formatter.html
             content_type: text/html

swiftmailer:
    transport: smtp
    host:      "%mailer_host%"
    username:  "%mailer_username%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    delivery_address: "%mailer_dev_recipient%"