UserBundle\Entity\User:
    type:  entity
    table: "`user`"
    repositoryClass: UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            length: null
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

