blog_admin_post_list:
    path:     /admin/blog
    defaults: { _controller: BlogBundle:AdminPost:list }
    methods: ['GET']

blog_admin_post_create:
    path:     /admin/blog/save
    defaults: { _controller: BlogBundle:AdminPost:save }
    methods: ['GET', 'POST']

blog_admin_post_edit:
    path:     /admin/blog/save/{slug}
    defaults: { _controller: BlogBundle:AdminPost:save }
    methods: ['GET', 'PUT']

blog_admin_post_preview:
    path:     /admin/blog/preview/{_locale}/{slug}
    defaults: { _controller: BlogBundle:AdminPost:preview }
    methods: ['GET']
    requirements:
        _locale: en|fr