BlogBundle\Entity\Post:
    type: entity
    table: "`post`"
    repositoryClass: BlogBundle\Repository\PostRepository
    id:
        id:
            type: integer
            length: null
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

    fields:
        englishTitle:
            type: string
            length: 150
            unique: true
            nullable: false
        englishSlug:
            type: string
            length: 150
            unique: true
            nullable: false
        frenchTitle:
            type: string
            length: 150
            unique: true
            nullable: false
        frenchSlug:
            type: string
            length: 150
            unique: true
            nullable: false
        englishContent:
            type: text
            unique: false
            nullable: true
        frenchContent:
            type: text
            unique: false
            nullable: true
        cover:
            type: string
            length: 255
            unique: false
            nullable: true
        category:
            type: string
            length: 150
            unique: false
            nullable: false
        publication:
            type: datetime
            length: null
            unique: false
            nullable: true

    manyToOne:
        user:
            targetEntity: UserBundle\Entity\User
            joinTable:
                referencedColumn: id
                nullable: false
                unique: false